version: "3.5"
networks:
  default:
    name: developchain

services:
  l1chain:
    image: ethereum/client-go
    ports:
      - "8545:8545"
    tty: true
    volumes:
      - ./l1chain/data:/data
      - ./l1chain/passwordfile:/passwordfile
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.api
      - --http.corsdomain='*'
      - --datadir=/data
      - --http.api='web3,eth,net,debug,personal'
      - --allow-insecure-unlock
      - --unlock=0x7dd17e8a1D7C69baB85F04F12A22d0866F8DfA5F
      - --mine
      - --password=/passwordfile
      - --miner.etherbase=0x7dd17e8a1D7C69baB85F04F12A22d0866F8DfA5F
  node1_ipfs:
    container_name: node1_ipfs
    image: ipfs/kubo
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./ipfs/node1/ipfs_staging:/export
      - ./ipfs/node1/ipfs_data:/data/ipfs
    environment:
      - IPFS_SWARM_KEY_FILE=/data/swarm.key
